[2023-10-11 12:45:53,505] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-11T12:45:52.608491+00:00 [queued]>
[2023-10-11 12:45:53,513] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-11T12:45:52.608491+00:00 [queued]>
[2023-10-11 12:45:53,514] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 12:45:53,518] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-10-11 12:45:53,519] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 12:45:53,531] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-10-11 12:45:52.608491+00:00
[2023-10-11 12:45:53,535] {standard_task_runner.py:52} INFO - Started process 1152 to run task
[2023-10-11 12:45:53,538] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2023-10-11T12:45:52.608491+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpatz8z0x8', '--error-file', '/tmp/tmp3ynm5_32']
[2023-10-11 12:45:53,539] {standard_task_runner.py:80} INFO - Job 31: Subtask load_seed_data_once
[2023-10-11 12:45:53,597] {task_command.py:369} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2023-10-11T12:45:52.608491+00:00 [running]> on host c2e542998ec2
[2023-10-11 12:45:53,704] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T12:45:52.608491+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T12:45:52.608491+00:00
[2023-10-11 12:45:53,706] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-10-11 12:45:53,708] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd .. && ls']
[2023-10-11 12:45:53,716] {subprocess.py:85} INFO - Output:
[2023-10-11 12:45:53,725] {subprocess.py:92} INFO - ***tmp9a0v3i4v
[2023-10-11 12:45:53,725] {subprocess.py:92} INFO - pymp-fislcah7
[2023-10-11 12:45:53,726] {subprocess.py:92} INFO - pymp-qcdzjw1v
[2023-10-11 12:45:53,727] {subprocess.py:92} INFO - tmp3ynm5_32
[2023-10-11 12:45:53,728] {subprocess.py:92} INFO - tmp8vnu40h4
[2023-10-11 12:45:53,728] {subprocess.py:96} INFO - Command exited with return code 0
[2023-10-11 12:45:53,761] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20231011T124552, start_date=20231011T124553, end_date=20231011T124553
[2023-10-11 12:45:53,791] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-11 12:45:53,824] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
